apiVersion: apps/v1
kind: Deployment
metadata:
  name: guia-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: guia-app
  template:
    metadata:
      labels:
        app: guia-app
    spec:
      containers:
        - name: guia-app
          image: raphaeltorresinfnet/infnet-guia:latest # não recomendado, só usando latest pra desenvolvimento
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: guia-app-service
spec:
  type: NodePort
  selector:
    app: guia-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
